CS186/hw2/localee/config/routes.rb
Cs186p2::Application.routes.draw do
  
  root :to => "home#index"
  
  match "login" => "sessions#new", :as => "login"
  match "logout" => "sessions#destroy", :as => "logout"
  match "signup" => "users#new", :as => "signup"
  
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  match "locations" => "app#locations_index", :as => "locations", :via => :get
  match "locations" => "app#locations_create", :as => "locations", :via => :post
  match "location/:id" => "app#location_show", :as => "location", :via => :get
  match "locations/:id/follow" => "app#location_follow", :as => "follow_location", :via => :post
  match "locations/:id/unfollow" => "app#location_unfollow", :as => "unfollow_location", :via => :post
  match "nearby_locations" => "app#nearby_locations_index", :as => "nearby_locations", :via => :post
  match "reports" => "app#reports_index", :as => "reports", :via => :get
  
  match "posts" => "app#posts_create", :as => "posts", :via => :post
  
  match "dashboard" => "app#dashboard", :as => "dashboard", :via => :get
  

end

CS186/hw2/localee/app/views/locations/_location.html.haml
.well
  %strong
    =link_to location[:name], location_path(location[:id])
  .pull-right
    =link_to "Unfollow", unfollow_location_path(location[:id]), :class => "btn btn-small", :method => :post
  %p
    =location[:latitude]
    ,
    =location[:longitude]

CS186/hw2/localee/app/views/locations/index.html.haml
.row
  .span12

    %ul.nav.nav-tabs
      %li.active
        %a{:data => {:toggle => "tab"}, :href => "#nearby_locations" } Nearby Locations
      %li
        %a{:data => {:toggle => "tab"}, :href => "#following_locations" } Following Locations
      %li
        %a{:data => {:toggle => "tab"}, :href => "#create_location", :id => "create_tab_btn" } Create New Location

    %div.tab-content
      %div#nearby_locations.tab-pane.active
        %h3 Nearby Locations
        %hr/
        #nearby-locations-map-canvas{:style => "width: 600px; height: 400px;"}
        %hr/
        #nearby-locations-list

      %div#following_locations.tab-pane
        %h3 Following Locations
        %hr/
        -@following_locations.each do |loc|
          =render "locations/location", :location => loc

      %div#create_location.tab-pane
        %h3 Create a new Location
        %hr/
        #new-location-map-canvas{:style => "width: 600px; height: 400px;"}
        =simple_form_for :location, :url => locations_path, :html => {:style => "form-horizontal"} do |f|
          =f.input :name
          =f.input :latitude, :as => :string, :input_html => {:readonly => "true"}
          =f.input :longitude, :as => :string, :input_html => {:readonly => "true"}
          =f.button :submit, "Create Location", :class => "btn btn-primary", :disabled => "true", :id => "create_location_btn"

CS186/hw2/localee/app/views/locations/show.html.haml
.page-header
  %h1
    =@location[:name]

.row
  .span12
    =simple_form_for :post, :url => posts_path do |f|
      =f.input :location_id, :as => :hidden, :input_html => { :value => @location[:id] }
      =f.input :text, :label => false, :input_html => {:class => "span12", :rows => 3}, :placeholder => "Type something cool here."
      =f.button :submit, "Create Post", :class => "btn btn-primary"

%hr/

-@posts.each do |p|
  =render "posts/post", :post => p