CS186/hw2/localee/config/routes.rb
Cs186p2::Application.routes.draw do
  
  root :to => "home#index"
  
  match "login" => "sessions#new", :as => "login"
  match "logout" => "sessions#destroy", :as => "logout"
  match "signup" => "users#new", :as => "signup"
  
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  match "locations" => "app#locations_index", :as => "locations", :via => :get
  match "locations" => "app#locations_create", :as => "locations", :via => :post
  match "location/:id" => "app#location_show", :as => "location", :via => :get
  match "locations/:id/follow" => "app#location_follow", :as => "follow_location", :via => :post
  match "locations/:id/unfollow" => "app#location_unfollow", :as => "unfollow_location", :via => :post
  match "nearby_locations" => "app#nearby_locations_index", :as => "nearby_locations", :via => :post
  match "reports" => "app#reports_index", :as => "reports", :via => :get
  
  match "posts" => "app#posts_create", :as => "posts", :via => :post
  
  match "dashboard" => "app#dashboard", :as => "dashboard", :via => :get
  

end

CS186/hw2/localee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

CS186/hw2/localee/app/helpers/application_helper.rb
module ApplicationHelper
end

CS186/hw2/localee/app/views/application/_header.html.haml
-if current_user
  =render :partial => "header_user"
-else
  =render :partial => "header_guest"

CS186/hw2/localee/app/views/application/_header_guest.html.haml
.navbar
  .navbar-inner
    =link_to nil, :class => "brand" do
      loCALee
    %ul.nav
      %li
        =link_to "Home", root_path
      %li
        =link_to "Reports", reports_path
    .pull-right
      %ul.nav
        %li
          =link_to "Login", login_path
        %li
          =link_to "Sign up", signup_path

CS186/hw2/localee/app/views/application/_header_user.html.haml
.navbar
  .navbar-inner
    =link_to nil, :class => "brand" do
      loCALee
    %ul.nav
      %li
        =link_to "Home", root_path
      %li
        =link_to "Locations", locations_path
      %li
        =link_to "Reports", reports_path
    .pull-right
      %ul.nav
        %li.dropdown
          =link_to "#", :data => {:toggle => "dropdown"} do
            %i.icon-user
            =current_user.email
            %b.caret
          %ul.dropdown-menu
            %li
              =link_to "Logout", logout_path, :method => :destroy